import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import Layout from '../components/layout';
import styles from '../styles/Home.module.css';

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <Layout title="Welcome to RedditStories!">
      <Head>
        <title>RedditStories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul className={styles.list}>
        <li className={styles.card}>
          <Link href="/r/talesfromtechsupport">
            <a>TalesFromTechSupport &rarr;</a>
          </Link>
        </li>

        <li className={styles.card}>
          <Link href="/r/gonewildstories">
            <a>GoneWildStories &rarr;</a>
          </Link>
        </li>
      </ul>
    </Layout>
  );
};

export default Home;
