import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import Layout from '../components/layout';
import styles from '../styles/Home.module.css';

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <Layout title="Welcome to RedditStories!">
      <Head>
        <title>RedditStories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.grid}>
        <Link href="/r/talesfromtechsupport">
          <a className={styles.card}>
            <h2>TalesFromTechSupport &rarr;</h2>
            <p>Read more!</p>
          </a>
        </Link>

        <Link href="/r/gonewildstories">
          <a className={styles.card}>
            <h2>GoneWildStories &rarr;</h2>
            <p>Read more!</p>
          </a>
        </Link>
      </div>
    </Layout>
  );
};

export default Home;
